### ISSUE TITLE
Difference between triggers and conditions? How to run continuously?

### ISSUE THREAD

**Issue by madb1lly** [bewee/macrozilla#17]
Hi @Galveston01,

Great new add-on! Thanks 😃

What's the difference between conditions and triggers for running macros? I notice that triggers only seem to accept things from your triggers selection item.

I tried putting the tick box, ticked, as a condition for a macro to make it run continuously but it doesn't seem to work. How can I make a macro run continuously? To give you some context, I want to use macros for more sophisticated rules than the rules engine allows, so I want them to be repeatedly evaluated.

Cheers 🙂

**Comment by Galveston01** [comment]
Hi @madb1lly,

Glad to hear the add-on works well for you😊

This add-on follows the approach of ECA-rules ("event-condition-action"). This means that whenever _one_ of the selected events gets fired (placed in "triggers", e.g. "property y of thing x was changed", "thing z was disconnected", "variable x was changed", "sunset started", etc) and _all_ the conditions are fullfilled (placed in "conditions", e.g. "property y of thing x is greater than 200", "variable x contains the number 42", "it is after sunset", etc) then the actions (e.g. "set property y of thing x to value 17", "wait 10 seconds", "increment variable x", etc) get executed consecutively. A time trigger already exists in the back end but has not yet been added to the front end. More could be added.

All in all, you needn't (and probably shouldn't) do something like
```
forever do:
  if property y of thing x is greater than 42 then:
    execute action a of thing z
  wait 10 seconds
```
but rather just trigger whenever "property y of thing x" changes and set "property y of thing x is greater than 42" as a condition and then use "execute action a of thing z" as the action.

So using a ticked checkbox as a condition will have exactly no effect compared to using no condition at all. And using it as a trigger is not possible since it just "does not trigger". However you could use a while loop and use the ticked checkbox as a condition and execute the macro manually once.

But I guess the ECA-format is just simpler and way faster than doing something like this. However, I can definitely see where a "on startup" trigger could come in handy, which would trigger whenever the gateway gets started. 

May I ask what exactly you try to achieve? :D

Regards :)

**Comment by madb1lly** [comment]
Hi @Galveston01,

Thank you for the explanation, triggers and conditions are clear now.

I'm trying to do things at present:
1. Calculate probable dew point in extraction duct based on room temperature and RH
2. Control extraction fan based on calculated dew point vs roof temperature to prevent condensation
3. Control extraction fan based on outside and indoor temperatures, to pull in warm air when it's warmer out than in

Following your advice, I structured these as follows:
1. On change of temperature, conditions=true, recalculate dew point
2. On change of roof temperature, if roof temperature is lower than dew point, set fan to on
3. On change of indoor or outdoor temperature, if outdoor is warmer than indoor, set fan to on

You said that a ticked tickbox in the condition field wouldn't make a difference, but I think my first macro wouldn't work without it.

I also found some odd behaviour with the < and > comparators, almost like they work the wrong way around. 

For both of those things I'm not certain yet - if I find something definite I'll raise an issue.

Cheers 🙂

**Comment by Galveston01** [comment]
Hi @madb1lly 

> Following your advice, I structured these as follows:

These sound quite reasonable. Would suggest you to use a variable to save the calculated probable dew point. I would be happy to get an update on how well these work in practice😊

> You said that a ticked tickbox in the condition field wouldn't make a difference, but I think my first macro wouldn't work without it.

Tested this using the following macro
![image](https://user-images.githubusercontent.com/44091658/95554157-fe2bc280-0a0f-11eb-8af8-0e4e1db6341e.png)
which on change of variable a produced the expected output
```
[info] Macro 4: {
  "title": "Starting macro execution",
  "message": "Initiated by: trigger variable"
}
[info] Macro 4, block 5: {
  "title": "executed",
  "message": "..."
}
[info] Macro 4: {
  "title": "Finished macro execution"
}
```

> I also found some odd behaviour with the < and > comparators, almost like they work the wrong way around.

Tested this using the following macro
![Screenshot 2020-10-09 at 09 09 43](https://user-images.githubusercontent.com/44091658/95553732-5d3d0780-0a0f-11eb-9488-a8135d100c3e.png)
which on manual execution produced the expected output
```
[info] Macro 10: {
  "title": "Starting macro execution",
  "message": "Initiated by: manual run"
}
[warn] Macro 10, block 4: {
  "title": "Using non-string value 'true' as string"
}
[info] Macro 10, block 4: {
  "title": "does > work?",
  "message": "true"
}
[info] Macro 10: {
  "title": "Finished macro execution"
}
```

If I was just missing something or if you find anything else opening an issue would be great 🙂

Regards :)

**Comment by madb1lly** [comment]
Hi @Galveston01.

Thanks for testing those two things. I've removed the tickbox and I've got a debug variable in the action to track if it the macro still gets executed.

For the comparator confusion, I think what happened is that I thought that if I clicked the "Play" button it would evaluate the condition, and only execute the action if the condition resolves to be true. However, the Play button executes the action directly, without evaluating the condition first, doesn't it?

Cheers 🙂

**Comment by Galveston01** [comment]
Hi @madb1lly,

You're right, manually executing does not check the conditions. It seems to me that this as well as the concept of triggers and conditions in general is not realized as intuitively as I had thought🙈 Do you have any ideas how this could be made more intuitively understandable?

Regards :)

**Comment by bewee** [comment]
> Do you have any ideas how this could be made more intuitively understandable?

Added a description of the behaviour of ECA rules and the play button to the README and hope this solves the problem

**Comment by madb1lly** [comment]
Hi @bewee,

Thank you for that and please excuse me for not replying before. I had intended to propose an update to the README but I (insert poor excuse here!) didn't. 😃

Cheers 🙂
